DEBUG    urllib3.connectionpool:connectionpool.py:232 Starting new HTTP connection (1): 127.0.0.1:6666
DEBUG    urllib3.connectionpool:connectionpool.py:465 http://127.0.0.1:6666 "POST /business/regist_form HTTP/1.1" 200 73
ERROR    root:test_business_register03.py:68 测试编号35,测试标题生日为不合理的时间,执行失败!实际结果{'code': 1013, 'msg': '该用户名、手机号、邮箱已经被注册'}
ERROR    root:test_business_register03.py:69 assert {'code': 1010...sg': '生日格式错误'} == {'code': 1013...、手机号、邮箱已经被注册'}
  Differing items:
  {'msg': '生日格式错误'} != {'msg': '该用户名、手机号、邮箱已经被注册'}
  {'code': 1010} != {'code': 1013}
  Full diff:
  - {'code': 1013, 'msg': '该用户名、手机号、邮箱已经被注册'}
  + {'code': 1010, 'msg': '生日格式错误'}
Traceback (most recent call last):
  File "D:\PythonWorkSpace\autotest\testcases\test_business_register03\test_business_register03.py", line 61, in test_register
    assert eval(case.expect) == res
AssertionError: assert {'code': 1010...sg': '生日格式错误'} == {'code': 1013...、手机号、邮箱已经被注册'}
  Differing items:
  {'msg': '生日格式错误'} != {'msg': '该用户名、手机号、邮箱已经被注册'}
  {'code': 1010} != {'code': 1013}
  Full diff:
  - {'code': 1013, 'msg': '该用户名、手机号、邮箱已经被注册'}
  + {'code': 1010, 'msg': '生日格式错误'}