{"name": "测试用户名输出错误的场景", "status": "passed", "parameters": [{"name": "case", "value": "<excel_utils.CaseData object at 0x000001FD8EF15B70>"}], "start": 1646041014112, "stop": 1646041014160, "uuid": "09f0e750-4b72-481f-ab60-c34792328129", "historyId": "9e59e38f75c692b8b2657fbe9ccbbea2", "testCaseId": "b62a022e3184708d2d40012e446c9b1d", "fullName": "test_login.TestLogin#test_login", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "登录的子模块"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-AM9Q0VH"}, {"name": "thread", "value": "9324-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}