DEBUG    urllib3.connectionpool:connectionpool.py:232 Starting new HTTP connection (1): 127.0.0.1:5000
DEBUG    urllib3.connectionpool:connectionpool.py:465 http://127.0.0.1:5000 "POST /register HTTP/1.1" 200 43
ERROR    root:test_register.py:41 测试编号1,测试用例标题正常流程,执行失败!实际结果是:{'code': 1008, 'msg': '用户名已存在'}
ERROR    root:test_register.py:42 assert {'code': 9999, 'msg': '注册成功'} == {'code': 1008...sg': '用户名已存在'}
  Differing items:
  {'msg': '注册成功'} != {'msg': '用户名已存在'}
  {'code': 9999} != {'code': 1008}
  Use -v to get the full diff
Traceback (most recent call last):
  File "D:\PythonWorkSpace\day16\test_excel_data03\test_register.py", line 38, in test_register
    assert eval(case.expect) == res
AssertionError: assert {'code': 9999, 'msg': '注册成功'} == {'code': 1008...sg': '用户名已存在'}
  Differing items:
  {'msg': '注册成功'} != {'msg': '用户名已存在'}
  {'code': 9999} != {'code': 1008}
  Use -v to get the full diff